'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization
Imports System.ComponentModel.DataAnnotations

<Assembly: EdmSchemaAttribute()>

Namespace Q306524RiaServicesValidation.Web
	#Region "Contexts"

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	Partial Public Class TestEntities
		Inherits ObjectContext
		#Region "Constructors"

		''' <summary>
		''' Initializes a new TestEntities object using the connection string found in the 'TestEntities' section of the application configuration file.
		''' </summary>
		Public Sub New()
			MyBase.New("name=TestEntities", "TestEntities")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		''' <summary>
		''' Initialize a new TestEntities object.
		''' </summary>
		Public Sub New(ByVal connectionString As String)
			MyBase.New(connectionString, "TestEntities")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		''' <summary>
		''' Initialize a new TestEntities object.
		''' </summary>
		Public Sub New(ByVal connection As EntityConnection)
			MyBase.New(connection, "TestEntities")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		#End Region

		#Region "Partial Methods"

		Partial Private Sub OnContextCreated()
		End Sub

		#End Region

		#Region "ObjectSet Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		Public ReadOnly Property TestTable() As ObjectSet(Of TestTable)
			Get
				If (_TestTable Is Nothing) Then
					_TestTable = MyBase.CreateObjectSet(Of TestTable)("TestTable")
				End If
				Return _TestTable
			End Get
		End Property
		Private _TestTable As ObjectSet(Of TestTable)

		#End Region
		#Region "AddTo Methods"

		''' <summary>
		''' Deprecated Method for adding a new object to the TestTable EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
		''' </summary>
		Public Sub AddToTestTable(ByVal testTable As TestTable)
			MyBase.AddObject("TestTable", testTable)
		End Sub

		#End Region
	End Class


	#End Region

	#Region "Entities"

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	<EdmEntityTypeAttribute(NamespaceName:="TestModel", Name:="TestTable"), Serializable(), DataContractAttribute(IsReference:=True)> _
	Partial Public Class TestTable
		Inherits EntityObject
		#Region "Factory Method"

		''' <summary>
		''' Create a new TestTable object.
		''' </summary>
		''' <param name="id">Initial value of the ID property.</param>
		''' <param name="number">Initial value of the Number property.</param>
		Public Shared Function CreateTestTable(ByVal id As Global.System.Guid, ByVal number As Global.System.Int32) As TestTable
			Dim testTable As New TestTable()
			testTable.ID = id
			testTable.Number = number
			Return testTable
		End Function

		#End Region
		#Region "Primitive Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property ID() As Global.System.Guid
			Get
				Return _ID
			End Get
			Set(ByVal value As System.Guid)
				If _ID <> value Then
					OnIDChanging(value)
					ReportPropertyChanging("ID")
					_ID = StructuralObject.SetValidValue(value)
					ReportPropertyChanged("ID")
					OnIDChanged()
				End If
			End Set
		End Property
		Private _ID As Global.System.Guid
		Partial Private Sub OnIDChanging(ByVal value As Global.System.Guid)
		End Sub
		Partial Private Sub OnIDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Text() As Global.System.String
			Get
				Return _Text
			End Get
			Set(ByVal value As System.String)
				OnTextChanging(value)
				ReportPropertyChanging("Text")
				_Text = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Text")
				OnTextChanged()
			End Set
		End Property
		Private _Text As Global.System.String
		Partial Private Sub OnTextChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnTextChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute(), Range(1, 10)> _
		Public Property Number() As Global.System.Int32
			Get
				Return _Number
			End Get
			Set(ByVal value As System.Int32)
				OnNumberChanging(value)
				ReportPropertyChanging("Number")
				_Number = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("Number")
				OnNumberChanged()
			End Set
		End Property
		Private _Number As Global.System.Int32
		Partial Private Sub OnNumberChanging(ByVal value As Global.System.Int32)
		End Sub
		Partial Private Sub OnNumberChanged()
		End Sub

		#End Region

	End Class

	#End Region

End Namespace
